### ISSUE TITLE
FAIRsharing as a tool to make your data FAIR

### ISSUE THREAD

**Issue by Drosophilic** [LibraryCarpentry/Top-10-FAIR#12]
Hi there, if you're still accepting changes/suggestions, may I propose we work together to include FAIRsharing in this? FAIRsharing works with the maintainers of resources to create and maintain manually curated metadata on standards (reporting guidelines, terminology artefacts, models and formats, metrics and identifier schema), databases (both knowledge-bases and repositories), and data policies (from funders and journal publishers). FAIRsharing provides this metadata to a growing ecosystem of FAIR providers, such as the FAIRshake evaluator tool, the FAIR evaluator tool (part of GO-FAIR), the Data Stewardship Wizard (part of GO-FAIR and ELIXIR), and more. FAIRsharing itself is funded by The Wellcome trust and is an ELIXIR Recommended Interoperability Resource, a member of EOSC-Life, has a working group in the RDA (which also has a recommended output), and has an implementation network in GO-FAIR.

I'd be happy to work with you to illustrate how FAIRsharing can be used to make data FAIR.

**Comment by katrinleinweber** [comment]
[Already included](https://github.com/LibraryCarpentry/Top-10-FAIR/search?q=FAIRsharing&unscoped_q=FAIRsharing) ;-)
