### ISSUE TITLE
imaging references .bib 

### ISSUE THREAD

**Issue by orchid00** [LibraryCarpentry/Top-10-FAIR#14]
@katrinleinweber,
do you think you can help me with my references? 
I worked with adding a bib file, it renders using pandoc (locally) but not showing the references here:
https://librarycarpentry.org/Top-10-FAIR/2019/06/27/imaging/
do you think I might need to move bib to another location?
You can find the two files here:
https://github.com/LibraryCarpentry/Top-10-FAIR/tree/master/_posts

Edit: I've used this neat guide: https://github.com/benmarwick/atom-for-scholarly-writing-with-markdown

Thank you,
Paula

**Comment by katrinleinweber** [comment]
Hi Paula,

GitHub Pages renders the _committed_ Markdown directly. I [don't think](https://github.blog/2016-04-01-a-look-behind-our-decision-to-standardize-on-a-single-markdown-engine-for-github-pages/) they use pandoc.

Presumably, you tried pandoc and the target format HTML or PDF locally when it worked? Please try the target format Markdown, and commit _that_ result to this repo. The conversion of an `@citation` has to either be done locally, or [using some online CI system with the bibliography-related commands](https://github.com/wdconinc/biosketch/blob/34a49bdd9d6e2dd2375a07256ddc3a3510a4f8d7/.travis.yml).

Cheers!
Katrin

**Comment by orchid00** [comment]
I need to investigate more, I couldn't come up with an answer :( but thanks for the resources @katrinleinweber 
I'll leave this open for me to look into it later.

**Comment by libcce** [comment]
Hi @orchid00 I initially tried to include references when I converted this repo .md files to pdf here  https://zenodo.org/record/2555498#.XU1nTpNKhR0. It just wasn't working out and I opted for the inline as this is what more people were using. If you find a way, would be nice to do this in the upcoming 2nd release.

**Comment by orchid00** [comment]
I didn't find a way to do it automatically, i'm afraid to say. I've sadly ended up doing the references manually. But I still have the .bib file in at some point I find the way. :P 

closing now.
