### ISSUE TITLE
separate domain specific content (imaging section)

### ISSUE THREAD

**Issue by jcolomb** [LibraryCarpentry/Top-10-FAIR#15]
hi,

I just had a rapid look at the imaging part. The information I was looking for is difficult to find, because of all the introduction about what is FAIR and so on.

I think it would be much more efficient to keep only domain specific information in there and get all generic ones in a different section. The music section seems to follow that idea...

**Comment by libcce** [comment]
Thanks @jcolomb the one on imaging is still a draft and @orchid00 is leading that. Thanks for the feedback and pinging @orchid00 so she can consider this.

**Comment by orchid00** [comment]
Hi Thanks for the feedback @jcolomb, What specific information where you trying to find? Did you find it? is the table of contents not enough to separate information?

**Comment by jcolomb** [comment]
Yep: recommendation for archiving imaging data (repository + format). Was at the very end, I think

The question is also more complex than I thought see #17

**Comment by orchid00** [comment]
cool, glad you found it! 
For any future search
8. Reusable data best practices
