### ISSUE TITLE
Reword "About" section?

### ISSUE THREAD

**Issue by evertrol** [LibraryCarpentry/Top-10-FAIR#20]
[suggestion]

I noticed that the "About" section doesn't really say up-front what this is about. Since the front page just throws you a set of links to sections, "About" should really do that. It is somewhat mentioned in the text, but it is more a description of the history of this project.

An opening paragraph stating what Top-10-FAIR is about would be nice. Perhaps one or two sentences from that paragraph could be copied onto the front page as well, which saves the new visitor a click to "About"; the same sentence(s) could be copied into the README file as well.

The same goes for the page description, which is currently just a copy of the first paragraph in the "About" section (and is displayed by e.g. Google in the search results).

**Comment by libcce** [comment]
It's a good suggestion @evertrol 😄 @ragamouf would you be interested in working on a pull request? Thought you might want to give it a try?

**Comment by libcce** [comment]
Hi @evertrol have a look at https://librarycarpentry.org/Top-10-FAIR/. Is this what you were thinking? Thanks!

**Comment by evertrol** [comment]
I'm afraid that's not what I'm looking for: it just copies the first "story" paragraph from /about, which isn't too clear about what *exactly* this is. That is, it reads like (paraphrasing):  "A long time ago, in a country far away, there once was ...". 

I'm thinking more of a one-(two-)liner such as:
"The top 10 Things lists 10 items that (scientists) can do to make their data and software FAIR: Findable, Accessible, Interoperable and Reusable. Each field has its own specific list."

(Think about it: the top-10-FAIR front page doesn't even say what FAIR is. If I point someone to this page to learn about these things, they'll find an acronym that doesn't really mean anything. And FAIR isn't even explained in /about!)

The same kind of one-liner could also be at the start of About, then a header "History" or "Origin", then the original text (The "About" title should probably be "About the Top 10 FAIR Data & Software Things" to be a self-consistent title).
Similar, I'd put such a one-liner directly at the top of the GitHub README file, where it now says "Top 10 FAIR Data & Software Things is hosted by Library Carpentry and maintained by the Sprinters." So that it's clear up-front in the README what this is about.

**Comment by libcce** [comment]
Hi @evertrol thanks for the additional feedback. I confess that was a late night commit but based on your feedback I think it is looking more like what you suggested. If you want to make a further tweak, please feel free to open a pull request 😄 

If you have an idea of a one-liner we can use on the readme and about pages, please also submit PRs or paste it here. Yes, you are absolutely right. This was on my to do list at some point to add more info about what FAIR is as I noticed what you did and thanks for the reminder!

**Comment by evertrol** [comment]
Yes, that's more what I had in mind. I hope (assume) that other people overall agree.

I'll create a PR for the other pieces, but I'm pretty sure that I'll just copy your paragraph and insert that into the relevant places; I think it's concise enough that it doesn't detract from other parts.

**Comment by libcce** [comment]
Thanks @evertrol! I'm closing this issue and thanks for submitting the separate issues/PRs!
